language: node_js
node_js:
  - "10"
install:
  - yarn global add travis-ci-cloudfront-invalidation gatsby-cli
  - yarn
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  s3_region: "us-west-2"
  bucket: "grayson.cash"
  paths:
    - $(git ls-files -o | tr "\n" ":")
  local_dir: public
  skip_cleanup: true
branches:
  only:
    - master
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CF_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
